### ISSUE TITLE
patool error

### ISSUE THREAD

**Issue by janvib27** [chen0040/keras-video-classifier-web-api#9]
I have created an environment and executing as instructed in Github.
ubuntu:18.04
python 3.6
On executing this command I am getting the following error:
python vgg16_bidirectional_lstm_train.py 
Using TensorFlow backend.
unzipping ucf file
patool: Extracting very_large_data/UCF101.rar ...
Traceback (most recent call last):
  File "vgg16_bidirectional_lstm_train.py", line 38, in <module>
    main()
  File "vgg16_bidirectional_lstm_train.py", line 27, in main
    load_ucf(input_dir_path)
  File "../keras_video_classifier/library/utility/ucf/UCF101_loader.py", line 75, in load_ucf
    download_ucf(data_dir_path)
  File "../keras_video_classifier/library/utility/ucf/UCF101_loader.py", line 34, in download_ucf
    patoolib.extract_archive(ucf_rar, outdir=data_dir_path)
  File "/home/dipesh/anaconda3/lib/python3.6/site-packages/patoolib/__init__.py", line 684, in extract_archive
    return _extract_archive(archive, verbosity=verbosity, interactive=interactive, outdir=outdir, program=program)
  File "/home/dipesh/anaconda3/lib/python3.6/site-packages/patoolib/__init__.py", line 470, in _extract_archive
    program = find_archive_program(format, 'extract', program=program)
  File "/home/dipesh/anaconda3/lib/python3.6/site-packages/patoolib/__init__.py", line 336, in find_archive_program
    raise util.PatoolError("could not find an executable program to %s format %s; candidates are (%s)," % (command, format, ",".join(programs)))
patoolib.util.PatoolError: could not find an executable program to extract format rar; candidates are (rar,unrar,7z),
Kindly help me resolve this issue. Thanks in advance.

**Comment by tianjihuimou** [comment]
Have you solved this problem? I have met it, too

**Comment by LiveNL** [comment]
The actual error seems to appear here:
`patoolib.util.PatoolError: could not find an executable program to extract format rar; candidates are (rar,unrar,7z),`

this can be resolved by installing one of the proposed candidates (for example; `brew install unrar`)

**Comment by SheldonXin** [comment]
@janvib27 hey,bro,I met the same problem with you,do you solve it?

**Comment by sasikanth513** [comment]
`brew install unrar` worked for me on OS X

**Comment by tanujdhiman** [comment]
Hello all 
I'm also using `Ubuntu` And getting this error. How did you resolve this ?

**Comment by Thijxx** [comment]
> Hello all I'm also using `Ubuntu` And getting this error. How did you resolve this ?

you can install unrar with `sudo apt install unrar`


_this issue comes up high on google so I necroposted to it_

**Comment by rajat709** [comment]
Hello @Thijxx 
I have installed both rar and unrar on Colab and I'm currently working on repacking a zip file into a rar format. However, when using the patoolib.repack_archive() function with verbosity set to 0, I encounter the following error: 'PatoolError: could not find an executable program to create format rar; candidates are (rar)'. Do you have any suggestions on how to resolve this issue?

**Comment by Thijxx** [comment]
> Hello @Thijxx I have installed both rar and unrar on Colab and I'm currently working on repacking a zip file into a rar format. However, when using the patoolib.repack_archive() function with verbosity set to 0, I encounter the following error: 'PatoolError: could not find an executable program to create format rar; candidates are (rar)'. Do you have any suggestions on how to resolve this issue?

does it return something when you run `which rar`?

**Comment by rajat709** [comment]
Yes, it gives the path where rar files stored.

**Comment by Thijxx** [comment]
> could not find an executable program to create format rar; candidates are (rar)'

Then I don't know what is happening, you may want to try StackOverflow, I don't think the problem is directly related to code in this repo
